Print("Example 1\n\n");
F := FreeGroup("s","t");
G := F/ParseRelators(F,"1=s^3=t^2");
D := DerivedSubgroup(G);
A := G/D;
IsAbelian(A);
Size(A);
IdGroup(A);
AbelianInvariants(G);
AbelianInvariants(D);
Print("Example 2\n\n");
F := FreeGroup("a","b","c");
G := F/ParseRelators(F,"1=[a,b]=[a,c]=[b,c]=(ab)^12=(ac)^20");
Size(G);
AbelianInvariants(G);
IsAbelian(G);
